apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: default

replicas:
- count: 1
  name: demoapp

images:
- name: ilolicon/demoapp
  newTag: v1.0.0

configMapGenerator:
- files:
  - config/config.yaml
  name: demoapp

labels:
- includeSelectors: true
  pairs:
    app: demoapp
