apiVersion: v1
kind: Service
metadata:
  name: demoapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
