name: Github Actions Demo
run-name: ${{ github.event_name }}-${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files in respository
        run: |
          ls -al ${{ github.workspace }}