name: Github Actions Demo
run-name: ${{ github.event_name }}-${{ github.actor }}
on:
  push:
    tags:
      - v*
jobs:
  deploy_prod:
    name: Deploy to production
    if: endsWith(github.ref, '-prod')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DEPLOY PRODUCTION
        run: |
          echo "Deploying ${{ github.ref }} to production"
          echo "Current version: $(cat ./VERSION)"

  deploy_test:
    name: Deploy to test
    if: endsWith(github.ref, '-test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DEPLOY TEST
        run: |
          echo "Deploying ${{ github.ref }} to production"
          echo "Current version: $(cat ./VERSION)"

  printenv:
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variables
        run: |
          echo "GITHUB_WORKFLOW=${{ github.workflow }}"
          echo "GITHUB_RUN_ID=${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
          echo "GITHUB_ACTION=${{ github.action }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REF=${{ github.ref }}"
