name: Demoapp CI
run-name: ${{ github.event_name }}-${{ github.actor }}
on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  build-and-push:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push
        run: |
          make build docker

      - name: Echo build information
        run: |
          echo "Built and pushed version: $(cat ./VERSION)"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REF=${{ github.ref }}"
