name: 🚀 APP CI
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login Alibaba Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build And Push
        run: |
          make all && make docker

      - name: Echo build information
        run: |
          echo "Built and pushed version: $(cat ./VERSION)"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REF=${{ github.ref }}"
