name: Github Actions Demo
run-name: ${{ github.event_name }}-${{ github.actor }}
on:
  push:
    branches:
      - main
    tags:
       - v* 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch tag
        run: |
          echo "当前触发Tag：${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/tags/v1.0.0-prod" ]]; then
            echo "部署到环境: production"
          elif [[ "${{ github.ref }}" == "refs/tags/v1.0.0-test" ]]; then
            echo "部署到环境: test"
          fi
      - name: Echo environment variables
        run: |
          echo "GITHUB_WORKFLOW=${{ github.workflow }}"
          echo "GITHUB_RUN_ID=${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
          echo "GITHUB_ACTION=${{ github.action }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REF=${{ github.ref }}"