name: Github Actions Demo
run-name: ${{ github.event_name }}-${{ github.actor }}
on:
  push:
    branches:
      - main
    tags:
       - v* 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files in respository
        run: |
          ls -al ${{ github.workspace }}
      - name: Echo environment variables
        run: |
          echo "GITHUB_WORKFLOW=${{ github.workflow }}"
          echo "GITHUB_RUN_ID=${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
          echo "GITHUB_ACTION=${{ github.action }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REF=${{ github.ref }}"